# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 新增文章
POST {{url}}:{{searchPort}}/search/save
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "title": "测试文章",
  "content": "测试文章内容",
  "state": "0"
}

### 查询文章
GET {{url}}:{{searchPort}}/search/测试/1/10
Accept: application/json
Content-Type: application/json;charset=UTF-8
