# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 获取验证码
POST {{url}}:{{userPort}}/user/sendsms/1383838438
Accept: application/json
Content-Type: application/json;charset=UTF-8


### 普通用户注册
POST {{url}}:{{userPort}}/user/register/772249
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "mobile": "1383838438",
  "password": "123",
  "nickname": "测试用户"
}

### 普通用户登录
POST {{url}}:{{userPort}}/user/login
Content-Type: application/x-www-form-urlencoded

mobile=1383838438&password=123

### 管理员注册
POST {{url}}:{{userPort}}/admin/register
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "loginname": "1383838438",
  "password": "123",
  "state": "1"
}

### 管理员登录
POST {{url}}:{{userPort}}/admin/login
Content-Type: application/x-www-form-urlencoded

loginName=1383838438&password=123

### 管理员删除用户
DELETE {{url}}:{{userPort}}/admin/1170648896125407232
#Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTcwNjQ4ODk2MTI1NDA3MjMyIiwic3ViIjoiMTM4MzgzODQzOCIsImlhdCI6MTU2NzkzOTg4OSwicm9sZXMiOiJhZG1pbiIsImV4cCI6MTU2Nzk0MDI0OX0.Qhq51P8EIg0uKWo8N44ScHfS_jmwvYl8UeIA6_BX6RU
###
